//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSEMAddIn.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OSEMAddIn.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 A local item named  的本地化字符串。
        /// </summary>
        public static string A_local_item_named {
            get {
                return ResourceManager.GetString("A_local_item_named", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Active Events 的本地化字符串。
        /// </summary>
        public static string Active_Events {
            get {
                return ResourceManager.GetString("Active_Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Field (+) 的本地化字符串。
        /// </summary>
        public static string Add_Field {
            get {
                return ResourceManager.GetString("Add_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add File... 的本地化字符串。
        /// </summary>
        public static string Add_File {
            get {
                return ResourceManager.GetString("Add_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Folder... 的本地化字符串。
        /// </summary>
        public static string Add_Folder {
            get {
                return ResourceManager.GetString("Add_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Rule 的本地化字符串。
        /// </summary>
        public static string Add_Rule {
            get {
                return ResourceManager.GetString("Add_Rule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Script 的本地化字符串。
        /// </summary>
        public static string Add_Script {
            get {
                return ResourceManager.GetString("Add_Script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All (10 Years) 的本地化字符串。
        /// </summary>
        public static string All_10_Years {
            get {
                return ResourceManager.GetString("All_10_Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All changes saved 的本地化字符串。
        /// </summary>
        public static string All_changes_saved {
            get {
                return ResourceManager.GetString("All_changes_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All Files (No Filter) 的本地化字符串。
        /// </summary>
        public static string All_Files_No_Filter {
            get {
                return ResourceManager.GetString("All_Files_No_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  already exists. How would you like to proceed? 的本地化字符串。
        /// </summary>
        public static string already_exists_How_would_you_like_to_proceed {
            get {
                return ResourceManager.GetString("already_exists_How_would_you_like_to_proceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Archive Event 的本地化字符串。
        /// </summary>
        public static string Archive_Event {
            get {
                return ResourceManager.GetString("Archive_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Archive (.zip, .rar, .7z...) 的本地化字符串。
        /// </summary>
        public static string Archive_zip_rar_7z {
            get {
                return ResourceManager.GetString("Archive_zip_rar_7z", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Associated:  的本地化字符串。
        /// </summary>
        public static string Associated {
            get {
                return ResourceManager.GetString("Associated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Associated Template (Optional) 的本地化字符串。
        /// </summary>
        public static string Associated_Template_Optional {
            get {
                return ResourceManager.GetString("Associated_Template_Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attachments 的本地化字符串。
        /// </summary>
        public static string Attachments {
            get {
                return ResourceManager.GetString("Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attempts to extract only the latest reply content, removing history. 的本地化字符串。
        /// </summary>
        public static string Attempts_to_extract_only_the_l_418b31 {
            get {
                return ResourceManager.GetString("Attempts_to_extract_only_the_l_418b31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto-generated JSON field structure to tell LLM which fields to extract. 的本地化字符串。
        /// </summary>
        public static string Auto_generated_JSON_field_stru_56821c {
            get {
                return ResourceManager.GetString("Auto_generated_JSON_field_stru_56821c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Available Variables 的本地化字符串。
        /// </summary>
        public static string Available_Variables {
            get {
                return ResourceManager.GetString("Available_Variables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ← Back to List 的本地化字符串。
        /// </summary>
        public static string Back_to_List {
            get {
                return ResourceManager.GetString("Back_to_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backup export successful! 的本地化字符串。
        /// </summary>
        public static string Backup_export_successful {
            get {
                return ResourceManager.GetString("Backup_export_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backup import successful! Please restart add-in or refresh UI to see updates. 的本地化字符串。
        /// </summary>
        public static string Backup_import_successful_Pleas_5048f2 {
            get {
                return ResourceManager.GetString("Backup_import_successful_Pleas_5048f2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Basic fields for general events. 的本地化字符串。
        /// </summary>
        public static string Basic_fields_for_general_events {
            get {
                return ResourceManager.GetString("Basic_fields_for_general_events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Besides default Inbox and Sent Items, you can add other folders to monitor here. 的本地化字符串。
        /// </summary>
        public static string Besides_default_Inbox_and_Sent_bab4c6 {
            get {
                return ResourceManager.GetString("Besides_default_Inbox_and_Sent_bab4c6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {Binding Status, StringFormat=Status: {0}} 的本地化字符串。
        /// </summary>
        public static string Binding_Status_StringFormat_Status_0 {
            get {
                return ResourceManager.GetString("Binding_Status_StringFormat_Status_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browse... 的本地化字符串。
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot Open Email 的本地化字符串。
        /// </summary>
        public static string Cannot_Open_Email {
            get {
                return ResourceManager.GetString("Cannot_Open_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot open file: {0} 的本地化字符串。
        /// </summary>
        public static string Cannot_open_file_ex_Message {
            get {
                return ResourceManager.GetString("Cannot_open_file_ex_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change Event Title 的本地化字符串。
        /// </summary>
        public static string Change_Event_Title {
            get {
                return ResourceManager.GetString("Change_Event_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear Filter 的本地化字符串。
        /// </summary>
        public static string Clear_Filter {
            get {
                return ResourceManager.GetString("Clear_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear Template Override 的本地化字符串。
        /// </summary>
        public static string Clear_Template_Override {
            get {
                return ResourceManager.GetString("Clear_Template_Override", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Common Files 的本地化字符串。
        /// </summary>
        public static string Common_Files {
            get {
                return ResourceManager.GetString("Common_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Complete Selected 的本地化字符串。
        /// </summary>
        public static string Complete_Selected {
            get {
                return ResourceManager.GetString("Complete_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Completed Events 的本地化字符串。
        /// </summary>
        public static string Completed_Events {
            get {
                return ResourceManager.GetString("Completed_Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copied non-empty Json keys to clipboard 的本地化字符串。
        /// </summary>
        public static string Copied_non_empty_Json_keys_to_clipboard {
            get {
                return ResourceManager.GetString("Copied_non_empty_Json_keys_to_clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy 的本地化字符串。
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy failed: {0} 的本地化字符串。
        /// </summary>
        public static string Copy_failed_ex_Message {
            get {
                return ResourceManager.GetString("Copy_failed_ex_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create Event Folder (Enter folder name) 的本地化字符串。
        /// </summary>
        public static string Create_Event_Folder_Enter_folder_name {
            get {
                return ResourceManager.GetString("Create_Event_Folder_Enter_folder_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current Prompt does not contain {{MAIL_BODY}} or {{MAIL_BODY_LATEST}}.\nThis means LLM may not get email body content.\n\nConfirm save? 的本地化字符串。
        /// </summary>
        public static string Current_Prompt_does_not_contai_b912e4 {
            get {
                return ResourceManager.GetString("Current_Prompt_does_not_contai_b912e4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current Template Only 的本地化字符串。
        /// </summary>
        public static string Current_Template_Only {
            get {
                return ResourceManager.GetString("Current_Template_Only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom Monitored Folders 的本地化字符串。
        /// </summary>
        public static string Custom_Monitored_Folders {
            get {
                return ResourceManager.GetString("Custom_Monitored_Folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dashboard Structure 的本地化字符串。
        /// </summary>
        public static string Dashboard_Structure {
            get {
                return ResourceManager.GetString("Dashboard_Structure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dashboard Templates 的本地化字符串。
        /// </summary>
        public static string Dashboard_Templates {
            get {
                return ResourceManager.GetString("Dashboard_Templates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Event 的本地化字符串。
        /// </summary>
        public static string Delete_Event {
            get {
                return ResourceManager.GetString("Delete_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Rule 的本地化字符串。
        /// </summary>
        public static string Delete_Rule {
            get {
                return ResourceManager.GetString("Delete_Rule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Selected Field 的本地化字符串。
        /// </summary>
        public static string Delete_Selected_Field {
            get {
                return ResourceManager.GetString("Delete_Selected_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description: 的本地化字符串。
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email Body (Full) 的本地化字符串。
        /// </summary>
        public static string Email_Body_Full {
            get {
                return ResourceManager.GetString("Email_Body_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email Body (Latest Only) 的本地化字符串。
        /// </summary>
        public static string Email_Body_Latest_Only {
            get {
                return ResourceManager.GetString("Email_Body_Latest_Only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email Name 的本地化字符串。
        /// </summary>
        public static string Email_Name {
            get {
                return ResourceManager.GetString("Email_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email Pool 的本地化字符串。
        /// </summary>
        public static string Email_Pool {
            get {
                return ResourceManager.GetString("Email_Pool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email Subject 的本地化字符串。
        /// </summary>
        public static string Email_Subject {
            get {
                return ResourceManager.GetString("Email_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email Unavailable 的本地化字符串。
        /// </summary>
        public static string Email_Unavailable {
            get {
                return ResourceManager.GetString("Email_Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End and Archive Event 的本地化字符串。
        /// </summary>
        public static string End_and_Archive_Event {
            get {
                return ResourceManager.GetString("End_and_Archive_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Endpoint e.g. https://api.example.com/v1/chat/completions 的本地化字符串。
        /// </summary>
        public static string Endpoint_e_g_https_api_example_8affd9 {
            get {
                return ResourceManager.GetString("Endpoint_e_g_https_api_example_8affd9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter custom Info content 的本地化字符串。
        /// </summary>
        public static string Enter_custom_Info_content {
            get {
                return ResourceManager.GetString("Enter_custom_Info_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter model name directly, e.g., llama3:8b. 的本地化字符串。
        /// </summary>
        public static string Enter_model_name_directly_e_g_llama3_8b {
            get {
                return ResourceManager.GetString("Enter_model_name_directly_e_g_llama3_8b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error opening email, please try again later. 的本地化字符串。
        /// </summary>
        public static string Error_opening_email_please_try_again_later {
            get {
                return ResourceManager.GetString("Error_opening_email_please_try_again_later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Event Attachments 的本地化字符串。
        /// </summary>
        public static string Event_Attachments {
            get {
                return ResourceManager.GetString("Event_Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Event Dashboard Data 的本地化字符串。
        /// </summary>
        public static string Event_Dashboard_Data {
            get {
                return ResourceManager.GetString("Event_Dashboard_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Event Files 的本地化字符串。
        /// </summary>
        public static string Event_Files {
            get {
                return ResourceManager.GetString("Event_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Event ID 的本地化字符串。
        /// </summary>
        public static string Event_ID {
            get {
                return ResourceManager.GetString("Event_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Event Manager 的本地化字符串。
        /// </summary>
        public static string Event_Manager {
            get {
                return ResourceManager.GetString("Event_Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Event Range 的本地化字符串。
        /// </summary>
        public static string Event_Range {
            get {
                return ResourceManager.GetString("Event_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Event {0} does not exist. 的本地化字符串。
        /// </summary>
        public static string Event_record_EventId_does_not_exist {
            get {
                return ResourceManager.GetString("Event_record_EventId_does_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Event Template: 的本地化字符串。
        /// </summary>
        public static string Event_Template {
            get {
                return ResourceManager.GetString("Event_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Example dashboard fields for typical freight orders. 的本地化字符串。
        /// </summary>
        public static string Example_dashboard_fields_for_t_7331d7 {
            get {
                return ResourceManager.GetString("Example_dashboard_fields_for_t_7331d7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Example script: Extract HAWB fields from PDF attachments. 的本地化字符串。
        /// </summary>
        public static string Example_script_Extract_HAWB_fi_402944 {
            get {
                return ResourceManager.GetString("Example_script_Extract_HAWB_fi_402944", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Excel Spreadsheet (.xls, .xlsx, .csv) 的本地化字符串。
        /// </summary>
        public static string Excel_Spreadsheet_xls_xlsx_csv {
            get {
                return ResourceManager.GetString("Excel_Spreadsheet_xls_xlsx_csv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export 的本地化字符串。
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export all current settings (except templates, prompts, scripts, LLM config) and event list. 的本地化字符串。
        /// </summary>
        public static string Export_all_current_settings_ex_c4a3e1 {
            get {
                return ResourceManager.GetString("Export_all_current_settings_ex_c4a3e1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export All Templates 的本地化字符串。
        /// </summary>
        public static string Export_All_Templates {
            get {
                return ResourceManager.GetString("Export_All_Templates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export Backup... 的本地化字符串。
        /// </summary>
        public static string Export_Backup {
            get {
                return ResourceManager.GetString("Export_Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export completed. 的本地化字符串。
        /// </summary>
        public static string Export_completed {
            get {
                return ResourceManager.GetString("Export_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export Content 的本地化字符串。
        /// </summary>
        public static string Export_Content {
            get {
                return ResourceManager.GetString("Export_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export failed: {0} 的本地化字符串。
        /// </summary>
        public static string Export_failed_ex_Message {
            get {
                return ResourceManager.GetString("Export_failed_ex_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export Folder Naming 的本地化字符串。
        /// </summary>
        public static string Export_Folder_Naming {
            get {
                return ResourceManager.GetString("Export_Folder_Naming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export/Import 的本地化字符串。
        /// </summary>
        public static string Export_Import {
            get {
                return ResourceManager.GetString("Export_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export Options 的本地化字符串。
        /// </summary>
        public static string Export_Options {
            get {
                return ResourceManager.GetString("Export_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export Selected Template 的本地化字符串。
        /// </summary>
        public static string Export_Selected_Template {
            get {
                return ResourceManager.GetString("Export_Selected_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export successful! 的本地化字符串。
        /// </summary>
        public static string Export_successful {
            get {
                return ResourceManager.GetString("Export_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export Template Package 的本地化字符串。
        /// </summary>
        public static string Export_Template_Package {
            get {
                return ResourceManager.GetString("Export_Template_Package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 External Python Analysis Script 的本地化字符串。
        /// </summary>
        public static string External_Python_Analysis_Script {
            get {
                return ResourceManager.GetString("External_Python_Analysis_Script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extract HAWB related fields from email and attachments and output JSON: {{DASHBOARD_JSON}} 的本地化字符串。
        /// </summary>
        public static string Extract_HAWB_related_fields_fr_c126bf {
            get {
                return ResourceManager.GetString("Extract_HAWB_related_fields_fr_c126bf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extracting... 的本地化字符串。
        /// </summary>
        public static string Extracting {
            get {
                return ResourceManager.GetString("Extracting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extraction completed. 的本地化字符串。
        /// </summary>
        public static string Extraction_completed {
            get {
                return ResourceManager.GetString("Extraction_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extraction failed: {0} 的本地化字符串。
        /// </summary>
        public static string Extraction_failed_ex_Message {
            get {
                return ResourceManager.GetString("Extraction_failed_ex_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to add folder: {0} 的本地化字符串。
        /// </summary>
        public static string Failed_to_add_folder_ex_Message {
            get {
                return ResourceManager.GetString("Failed_to_add_folder_ex_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to create folder: {0} 的本地化字符串。
        /// </summary>
        public static string Failed_to_create_folder_ex_Message {
            get {
                return ResourceManager.GetString("Failed_to_create_folder_ex_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to load Ollama model list: {0} 的本地化字符串。
        /// </summary>
        public static string Failed_to_load_Ollama_model_list_ex_Message {
            get {
                return ResourceManager.GetString("Failed_to_load_Ollama_model_list_ex_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to update folder: {0} 的本地化字符串。
        /// </summary>
        public static string Failed_to_update_folder_ex_Message {
            get {
                return ResourceManager.GetString("Failed_to_update_folder_ex_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Field Name (Key) 的本地化字符串。
        /// </summary>
        public static string Field_Name_Key {
            get {
                return ResourceManager.GetString("Field_Name_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fields &amp; Regex 的本地化字符串。
        /// </summary>
        public static string Fields_Regex {
            get {
                return ResourceManager.GetString("Fields_Regex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Area 的本地化字符串。
        /// </summary>
        public static string File_Area {
            get {
                return ResourceManager.GetString("File_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Type Filter 的本地化字符串。
        /// </summary>
        public static string File_Type_Filter {
            get {
                return ResourceManager.GetString("File_Type_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filename 的本地化字符串。
        /// </summary>
        public static string Filename {
            get {
                return ResourceManager.GetString("Filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filter by Template 的本地化字符串。
        /// </summary>
        public static string Filter_by_Template {
            get {
                return ResourceManager.GetString("Filter_by_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filter Template 的本地化字符串。
        /// </summary>
        public static string Filter_Template {
            get {
                return ResourceManager.GetString("Filter_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Folder|*.* 的本地化字符串。
        /// </summary>
        public static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Folder does not exist: {0} 的本地化字符串。
        /// </summary>
        public static string Folder_does_not_exist_LocalFolderPath {
            get {
                return ResourceManager.GetString("Folder_does_not_exist_LocalFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Folder Name 的本地化字符串。
        /// </summary>
        public static string Folder_Name {
            get {
                return ResourceManager.GetString("Folder_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Folder update completed 的本地化字符串。
        /// </summary>
        public static string Folder_update_completed {
            get {
                return ResourceManager.GetString("Folder_update_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Force Activate 的本地化字符串。
        /// </summary>
        public static string Force_Activate {
            get {
                return ResourceManager.GetString("Force_Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 From 的本地化字符串。
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Full body content of the currently selected email (including history). 的本地化字符串。
        /// </summary>
        public static string Full_body_content_of_the_curre_6337dd {
            get {
                return ResourceManager.GetString("Full_body_content_of_the_curre_6337dd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Full Path 的本地化字符串。
        /// </summary>
        public static string Full_Path {
            get {
                return ResourceManager.GetString("Full_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FW: 的本地化字符串。
        /// </summary>
        public static string FW {
            get {
                return ResourceManager.GetString("FW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FW: 的本地化字符串。
        /// </summary>
        public static string FW_1 {
            get {
                return ResourceManager.GetString("FW_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FW: 的本地化字符串。
        /// </summary>
        public static string FW_2 {
            get {
                return ResourceManager.GetString("FW_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FW: 的本地化字符串。
        /// </summary>
        public static string FW_3 {
            get {
                return ResourceManager.GetString("FW_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General Info Extraction 的本地化字符串。
        /// </summary>
        public static string General_Info_Extraction {
            get {
                return ResourceManager.GetString("General_Info_Extraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General Template 的本地化字符串。
        /// </summary>
        public static string General_Template {
            get {
                return ResourceManager.GetString("General_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generate 的本地化字符串。
        /// </summary>
        public static string Generate {
            get {
                return ResourceManager.GetString("Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generate Folder 的本地化字符串。
        /// </summary>
        public static string Generate_Folder {
            get {
                return ResourceManager.GetString("Generate_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Global (All Templates) 的本地化字符串。
        /// </summary>
        public static string Global_All_Templates {
            get {
                return ResourceManager.GetString("Global_All_Templates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Global Script (Access all event data) 的本地化字符串。
        /// </summary>
        public static string Global_Script_Access_all_event_data {
            get {
                return ResourceManager.GetString("Global_Script_Access_all_event_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HAWB Detail Extraction 的本地化字符串。
        /// </summary>
        public static string HAWB_Detail_Extraction {
            get {
                return ResourceManager.GetString("HAWB_Detail_Extraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image (.png, .jpg, .bmp...) 的本地化字符串。
        /// </summary>
        public static string Image_png_jpg_bmp {
            get {
                return ResourceManager.GetString("Image_png_jpg_bmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import 的本地化字符串。
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import and Rename 的本地化字符串。
        /// </summary>
        public static string Import_and_Rename {
            get {
                return ResourceManager.GetString("Import_and_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import Backup... 的本地化字符串。
        /// </summary>
        public static string Import_Backup {
            get {
                return ResourceManager.GetString("Import_Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import backup file. Existing data kept, new data added, conflicts updated by timestamp. 的本地化字符串。
        /// </summary>
        public static string Import_backup_file_Existing_da_edc9d3 {
            get {
                return ResourceManager.GetString("Import_backup_file_Existing_da_edc9d3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import Backup (Merge Mode) 的本地化字符串。
        /// </summary>
        public static string Import_Backup_Merge_Mode {
            get {
                return ResourceManager.GetString("Import_Backup_Merge_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import Conflict 的本地化字符串。
        /// </summary>
        public static string Import_Conflict {
            get {
                return ResourceManager.GetString("Import_Conflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import failed: {0} 的本地化字符串。
        /// </summary>
        public static string Import_failed_ex_Message {
            get {
                return ResourceManager.GetString("Import_failed_ex_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import successful! 的本地化字符串。
        /// </summary>
        public static string Import_successful {
            get {
                return ResourceManager.GetString("Import_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import Template 的本地化字符串。
        /// </summary>
        public static string Import_Template {
            get {
                return ResourceManager.GetString("Import_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import Template Package 的本地化字符串。
        /// </summary>
        public static string Import_Template_Package {
            get {
                return ResourceManager.GetString("Import_Template_Package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Info 的本地化字符串。
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ← Insert 的本地化字符串。
        /// </summary>
        public static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert selected variable at cursor 的本地化字符串。
        /// </summary>
        public static string Insert_selected_variable_at_cursor {
            get {
                return ResourceManager.GetString("Insert_selected_variable_at_cursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keep Local (Skip) 的本地化字符串。
        /// </summary>
        public static string Keep_Local_Skip {
            get {
                return ResourceManager.GetString("Keep_Local_Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last Updated 的本地化字符串。
        /// </summary>
        public static string Last_Updated {
            get {
                return ResourceManager.GetString("Last_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Latest update on Event {{EventId}} 的本地化字符串。
        /// </summary>
        public static string Latest_update_on_Event_EventId {
            get {
                return ResourceManager.GetString("Latest_update_on_Event_EventId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LLM configuration saved 的本地化字符串。
        /// </summary>
        public static string LLM_configuration_saved {
            get {
                return ResourceManager.GetString("LLM_configuration_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LLM Model Config (Global) 的本地化字符串。
        /// </summary>
        public static string LLM_Model_Config_Global {
            get {
                return ResourceManager.GetString("LLM_Model_Config_Global", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LLM Settings 的本地化字符串。
        /// </summary>
        public static string LLM_Settings {
            get {
                return ResourceManager.GetString("LLM_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logistics Demo Template 的本地化字符串。
        /// </summary>
        public static string Logistics_Demo_Template {
            get {
                return ResourceManager.GetString("Logistics_Demo_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mark All Read 的本地化字符串。
        /// </summary>
        public static string Mark_All_Read {
            get {
                return ResourceManager.GetString("Mark_All_Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Missing Email Body Variable 的本地化字符串。
        /// </summary>
        public static string Missing_Email_Body_Variable {
            get {
                return ResourceManager.GetString("Missing_Email_Body_Variable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Model ID used for requests. 的本地化字符串。
        /// </summary>
        public static string Model_ID_used_for_requests {
            get {
                return ResourceManager.GetString("Model_ID_used_for_requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Model Name 的本地化字符串。
        /// </summary>
        public static string Model_Name {
            get {
                return ResourceManager.GetString("Model_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Monitored Folders 的本地化字符串。
        /// </summary>
        public static string Monitored_Folders {
            get {
                return ResourceManager.GetString("Monitored_Folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Event Notification 的本地化字符串。
        /// </summary>
        public static string New_Event_Notification {
            get {
                return ResourceManager.GetString("New_Event_Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Prompt 的本地化字符串。
        /// </summary>
        public static string New_Prompt {
            get {
                return ResourceManager.GetString("New_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Template 的本地化字符串。
        /// </summary>
        public static string New_Template {
            get {
                return ResourceManager.GetString("New_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No matching events to export. 的本地化字符串。
        /// </summary>
        public static string No_matching_events_to_export {
            get {
                return ResourceManager.GetString("No_matching_events_to_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No non-empty Json keys to copy 的本地化字符串。
        /// </summary>
        public static string No_non_empty_Json_keys_to_copy {
            get {
                return ResourceManager.GetString("No_non_empty_Json_keys_to_copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (No Subject Event) 的本地化字符串。
        /// </summary>
        public static string No_Subject_Event {
            get {
                return ResourceManager.GetString("No_Subject_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No template associated (will apply to all templates) 的本地化字符串。
        /// </summary>
        public static string No_template_associated_will_apply_to_all_templates {
            get {
                return ResourceManager.GetString("No_template_associated_will_apply_to_all_templates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ollama Local 的本地化字符串。
        /// </summary>
        public static string Ollama_Local {
            get {
                return ResourceManager.GetString("Ollama_Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ollama Model 的本地化字符串。
        /// </summary>
        public static string Ollama_Model {
            get {
                return ResourceManager.GetString("Ollama_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Outlook cannot find this email, it may have been moved or deleted. 的本地化字符串。
        /// </summary>
        public static string Outlook_cannot_find_this_email_9e5a34 {
            get {
                return ResourceManager.GetString("Outlook_cannot_find_this_email_9e5a34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Overwrite Local 的本地化字符串。
        /// </summary>
        public static string Overwrite_Local {
            get {
                return ResourceManager.GetString("Overwrite_Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;p&gt;Dear Customer,&lt;/p&gt;&lt;p&gt;Here is the latest update for Event {{EventId}}...&lt;/p&gt; 的本地化字符串。
        /// </summary>
        public static string p_Dear_Customer_p_p_Here_is_th_713eca {
            get {
                return ResourceManager.GetString("p_Dear_Customer_p_p_Here_is_th_713eca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;p&gt;Hello,&lt;/p&gt;&lt;p&gt;We have received your email and will process it as soon as possible.&lt;/p&gt; 的本地化字符串。
        /// </summary>
        public static string p_Hello_p_p_We_have_received_y_5e6bbc {
            get {
                return ResourceManager.GetString("p_Hello_p_p_We_have_received_y_5e6bbc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Participants (Emails, semicolon separated) 的本地化字符串。
        /// </summary>
        public static string Participants_Emails_semicolon_separated {
            get {
                return ResourceManager.GetString("Participants_Emails_semicolon_separated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Path 的本地化字符串。
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PDF Document (.pdf) 的本地化字符串。
        /// </summary>
        public static string PDF_Document_pdf {
            get {
                return ResourceManager.GetString("PDF_Document_pdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please extract dashboard fields based on the following email content: {{DASHBOARD_JSON}} 的本地化字符串。
        /// </summary>
        public static string Please_extract_dashboard_field_6914e4 {
            get {
                return ResourceManager.GetString("Please_extract_dashboard_field_6914e4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select a template to export first. 的本地化字符串。
        /// </summary>
        public static string Please_select_a_template_to_export_first {
            get {
                return ResourceManager.GetString("Please_select_a_template_to_export_first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select an email folder. 的本地化字符串。
        /// </summary>
        public static string Please_select_an_email_folder {
            get {
                return ResourceManager.GetString("Please_select_an_email_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PPT Presentation (.ppt, .pptx) 的本地化字符串。
        /// </summary>
        public static string PPT_Presentation_ppt_pptx {
            get {
                return ResourceManager.GetString("PPT_Presentation_ppt_pptx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preferred Template 的本地化字符串。
        /// </summary>
        public static string Preferred_Template {
            get {
                return ResourceManager.GetString("Preferred_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preparing to refresh... 的本地化字符串。
        /// </summary>
        public static string Preparing_to_refresh {
            get {
                return ResourceManager.GetString("Preparing_to_refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Priority 的本地化字符串。
        /// </summary>
        public static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Processing ({0}/{1}): {2} 的本地化字符串。
        /// </summary>
        public static string Processing_current_total_fileVm_FileName {
            get {
                return ResourceManager.GetString("Processing_current_total_fileVm_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prompt Content: 的本地化字符串。
        /// </summary>
        public static string Prompt_Content {
            get {
                return ResourceManager.GetString("Prompt_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prompt Management 的本地化字符串。
        /// </summary>
        public static string Prompt_Management {
            get {
                return ResourceManager.GetString("Prompt_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prompt management interface not implemented yet, will be available in future versions. 的本地化字符串。
        /// </summary>
        public static string Prompt_management_interface_no_c1825d {
            get {
                return ResourceManager.GetString("Prompt_management_interface_no_c1825d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prompt Name: 的本地化字符串。
        /// </summary>
        public static string Prompt_Name {
            get {
                return ResourceManager.GetString("Prompt_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Provider 的本地化字符串。
        /// </summary>
        public static string Provider {
            get {
                return ResourceManager.GetString("Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RE: 的本地化字符串。
        /// </summary>
        public static string RE {
            get {
                return ResourceManager.GetString("RE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RE: 的本地化字符串。
        /// </summary>
        public static string RE_1 {
            get {
                return ResourceManager.GetString("RE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RE: 的本地化字符串。
        /// </summary>
        public static string RE_2 {
            get {
                return ResourceManager.GetString("RE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RE: 的本地化字符串。
        /// </summary>
        public static string RE_3 {
            get {
                return ResourceManager.GetString("RE_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ready 的本地化字符串。
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ready 的本地化字符串。
        /// </summary>
        public static string Ready_1 {
            get {
                return ResourceManager.GetString("Ready_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Received Time 的本地化字符串。
        /// </summary>
        public static string Received_Time {
            get {
                return ResourceManager.GetString("Received_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Received Time 的本地化字符串。
        /// </summary>
        public static string Received_Time_1 {
            get {
                return ResourceManager.GetString("Received_Time_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recipient 的本地化字符串。
        /// </summary>
        public static string Recipient {
            get {
                return ResourceManager.GetString("Recipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh All 的本地化字符串。
        /// </summary>
        public static string Refresh_All {
            get {
                return ResourceManager.GetString("Refresh_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh Emails 的本地化字符串。
        /// </summary>
        public static string Refresh_Emails {
            get {
                return ResourceManager.GetString("Refresh_Emails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Regex Extraction: 的本地化字符串。
        /// </summary>
        public static string Regex_Extraction {
            get {
                return ResourceManager.GetString("Regex_Extraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Regex Rule 的本地化字符串。
        /// </summary>
        public static string Regex_Rule {
            get {
                return ResourceManager.GetString("Regex_Rule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reloading event data... 的本地化字符串。
        /// </summary>
        public static string Reloading_event_data {
            get {
                return ResourceManager.GetString("Reloading_event_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove File 的本地化字符串。
        /// </summary>
        public static string Remove_File {
            get {
                return ResourceManager.GetString("Remove_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove Selected 的本地化字符串。
        /// </summary>
        public static string Remove_Selected {
            get {
                return ResourceManager.GetString("Remove_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove this email 的本地化字符串。
        /// </summary>
        public static string Remove_this_email {
            get {
                return ResourceManager.GetString("Remove_this_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reopen 的本地化字符串。
        /// </summary>
        public static string Reopen {
            get {
                return ResourceManager.GetString("Reopen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reopen Event 的本地化字符串。
        /// </summary>
        public static string Reopen_Event {
            get {
                return ResourceManager.GetString("Reopen_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Requesting LLM extraction... 的本地化字符串。
        /// </summary>
        public static string Requesting_LLM_extraction {
            get {
                return ResourceManager.GetString("Requesting_LLM_extraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 180 Days 的本地化字符串。
        /// </summary>
        public static string Res_180_Days {
            get {
                return ResourceManager.GetString("Res_180_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 30 Days (Default) 的本地化字符串。
        /// </summary>
        public static string Res_30_Days_Default {
            get {
                return ResourceManager.GetString("Res_30_Days_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 45 Days 的本地化字符串。
        /// </summary>
        public static string Res_45_Days {
            get {
                return ResourceManager.GetString("Res_45_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 60 Days 的本地化字符串。
        /// </summary>
        public static string Res_60_Days {
            get {
                return ResourceManager.GetString("Res_60_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset Month 的本地化字符串。
        /// </summary>
        public static string Reset_Month {
            get {
                return ResourceManager.GetString("Reset_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run LLM Extraction 的本地化字符串。
        /// </summary>
        public static string Run_LLM_Extraction {
            get {
                return ResourceManager.GetString("Run_LLM_Extraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run Regex Extraction 的本地化字符串。
        /// </summary>
        public static string Run_Regex_Extraction {
            get {
                return ResourceManager.GetString("Run_Regex_Extraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run Script 的本地化字符串。
        /// </summary>
        public static string Run_Script {
            get {
                return ResourceManager.GetString("Run_Script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save All Changes 的本地化字符串。
        /// </summary>
        public static string Save_All_Changes {
            get {
                return ResourceManager.GetString("Save_All_Changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save and Close 的本地化字符串。
        /// </summary>
        public static string Save_and_Close {
            get {
                return ResourceManager.GetString("Save_and_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Config 的本地化字符串。
        /// </summary>
        public static string Save_Config {
            get {
                return ResourceManager.GetString("Save_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Location 的本地化字符串。
        /// </summary>
        public static string Save_Location {
            get {
                return ResourceManager.GetString("Save_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Prompt 的本地化字符串。
        /// </summary>
        public static string Save_Prompt {
            get {
                return ResourceManager.GetString("Save_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scope 的本地化字符串。
        /// </summary>
        public static string Scope {
            get {
                return ResourceManager.GetString("Scope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Script: 的本地化字符串。
        /// </summary>
        public static string Script {
            get {
                return ResourceManager.GetString("Script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Script Management 的本地化字符串。
        /// </summary>
        public static string Script_Management {
            get {
                return ResourceManager.GetString("Script_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Script Name: 的本地化字符串。
        /// </summary>
        public static string Script_Name {
            get {
                return ResourceManager.GetString("Script_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Script not found 的本地化字符串。
        /// </summary>
        public static string Script_not_found {
            get {
                return ResourceManager.GetString("Script_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Script Path: 的本地化字符串。
        /// </summary>
        public static string Script_Path {
            get {
                return ResourceManager.GetString("Script_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Searching for related subject emails... 的本地化字符串。
        /// </summary>
        public static string Searching_for_related_subject_emails {
            get {
                return ResourceManager.GetString("Searching_for_related_subject_emails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select columns to display or enter custom content 的本地化字符串。
        /// </summary>
        public static string Select_columns_to_display_or_enter_custom_content {
            get {
                return ResourceManager.GetString("Select_columns_to_display_or_enter_custom_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select File Types 的本地化字符串。
        /// </summary>
        public static string Select_File_Types {
            get {
                return ResourceManager.GetString("Select_File_Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Global Script 的本地化字符串。
        /// </summary>
        public static string Select_Global_Script {
            get {
                return ResourceManager.GetString("Select_Global_Script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Script 的本地化字符串。
        /// </summary>
        public static string Select_Script {
            get {
                return ResourceManager.GetString("Select_Script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Template 的本地化字符串。
        /// </summary>
        public static string Select_Template {
            get {
                return ResourceManager.GetString("Select_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sender 的本地化字符串。
        /// </summary>
        public static string Sender {
            get {
                return ResourceManager.GetString("Sender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sender name of the currently selected email. 的本地化字符串。
        /// </summary>
        public static string Sender_name_of_the_currently_selected_email {
            get {
                return ResourceManager.GetString("Sender_name_of_the_currently_selected_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Size 的本地化字符串。
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Standard Reply Template 的本地化字符串。
        /// </summary>
        public static string Standard_Reply_Template {
            get {
                return ResourceManager.GetString("Standard_Reply_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Subject 的本地化字符串。
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Subject of the currently selected email. 的本地化字符串。
        /// </summary>
        public static string Subject_of_the_currently_selected_email {
            get {
                return ResourceManager.GetString("Subject_of_the_currently_selected_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (?:Subject|主题|主旨|標題|제목|件名)\s*[:：]\s*(?&lt;subject&gt;.+(?:\r?\n[ \t]+.+)*) 的本地化字符串。
        /// </summary>
        public static string Subject_s_s_subject_r_n_t {
            get {
                return ResourceManager.GetString("Subject_s_s_subject_r_n_t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Syncing {0} conversations... 的本地化字符串。
        /// </summary>
        public static string Syncing_conversationIds_Count_conversations {
            get {
                return ResourceManager.GetString("Syncing_conversationIds_Count_conversations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System Backup &amp; Migration 的本地化字符串。
        /// </summary>
        public static string System_Backup_Migration {
            get {
                return ResourceManager.GetString("System_Backup_Migration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Template &amp; Config Editor 的本地化字符串。
        /// </summary>
        public static string Template_Config_Editor {
            get {
                return ResourceManager.GetString("Template_Config_Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Template Editor 的本地化字符串。
        /// </summary>
        public static string Template_Editor {
            get {
                return ResourceManager.GetString("Template_Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Template Name: 的本地化字符串。
        /// </summary>
        public static string Template_Name {
            get {
                return ResourceManager.GetString("Template_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Template Rule Manager 的本地化字符串。
        /// </summary>
        public static string Template_Rule_Manager {
            get {
                return ResourceManager.GetString("Template_Rule_Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Template Rules 的本地化字符串。
        /// </summary>
        public static string Template_Rules {
            get {
                return ResourceManager.GetString("Template_Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text File (.txt, .md, .rtf) 的本地化字符串。
        /// </summary>
        public static string Text_File_txt_md_rtf {
            get {
                return ResourceManager.GetString("Text_File_txt_md_rtf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This folder is already in the monitor list. 的本地化字符串。
        /// </summary>
        public static string This_folder_is_already_in_the_monitor_list {
            get {
                return ResourceManager.GetString("This_folder_is_already_in_the_monitor_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 To 的本地化字符串。
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Toggle Priority 的本地化字符串。
        /// </summary>
        public static string Toggle_Priority {
            get {
                return ResourceManager.GetString("Toggle_Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to parse selected email. 的本地化字符串。
        /// </summary>
        public static string Unable_to_parse_selected_email {
            get {
                return ResourceManager.GetString("Unable_to_parse_selected_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to start Python process. 的本地化字符串。
        /// </summary>
        public static string Unable_to_start_Python_process {
            get {
                return ResourceManager.GetString("Unable_to_start_Python_process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update Failed 的本地化字符串。
        /// </summary>
        public static string Update_Failed {
            get {
                return ResourceManager.GetString("Update_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update to Folder 的本地化字符串。
        /// </summary>
        public static string Update_to_Folder {
            get {
                return ResourceManager.GetString("Update_to_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Updating folder... 的本地化字符串。
        /// </summary>
        public static string Updating_folder {
            get {
                return ResourceManager.GetString("Updating_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Updating UI... 的本地化字符串。
        /// </summary>
        public static string Updating_UI {
            get {
                return ResourceManager.GetString("Updating_UI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Validating email availability... 的本地化字符串。
        /// </summary>
        public static string Validating_email_availability {
            get {
                return ResourceManager.GetString("Validating_email_availability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Word Document (.doc, .docx) 的本地化字符串。
        /// </summary>
        public static string Word_Document_doc_docx {
            get {
                return ResourceManager.GetString("Word_Document_doc_docx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outlook is busy processing items....
        /// </summary>
        public static string Outlook_is_busy_processing_items {
            get {
                return ResourceManager.GetString("Outlook_is_busy_processing_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Archived 的本地化字符串。
        /// </summary>
        public static string Archived {
            get {
                return ResourceManager.GetString("Archived", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 In Progress 的本地化字符串。
        /// </summary>
        public static string In_Progress {
            get {
                return ResourceManager.GetString("In_Progress", resourceCulture);
            }
        }
    }
}
